package com.example.greendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaodemo.bean.EventBean;
import com.example.greendaodemo.bean.HangupBean;
import com.example.greendaodemo.bean.StudentBean;

import com.example.greendaodemo.dao.EventBeanDao;
import com.example.greendaodemo.dao.HangupBeanDao;
import com.example.greendaodemo.dao.StudentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventBeanDaoConfig;
    private final DaoConfig hangupBeanDaoConfig;
    private final DaoConfig studentBeanDaoConfig;

    private final EventBeanDao eventBeanDao;
    private final HangupBeanDao hangupBeanDao;
    private final StudentBeanDao studentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventBeanDaoConfig = daoConfigMap.get(EventBeanDao.class).clone();
        eventBeanDaoConfig.initIdentityScope(type);

        hangupBeanDaoConfig = daoConfigMap.get(HangupBeanDao.class).clone();
        hangupBeanDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        eventBeanDao = new EventBeanDao(eventBeanDaoConfig, this);
        hangupBeanDao = new HangupBeanDao(hangupBeanDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);

        registerDao(EventBean.class, eventBeanDao);
        registerDao(HangupBean.class, hangupBeanDao);
        registerDao(StudentBean.class, studentBeanDao);
    }
    
    public void clear() {
        eventBeanDaoConfig.clearIdentityScope();
        hangupBeanDaoConfig.clearIdentityScope();
        studentBeanDaoConfig.clearIdentityScope();
    }

    public EventBeanDao getEventBeanDao() {
        return eventBeanDao;
    }

    public HangupBeanDao getHangupBeanDao() {
        return hangupBeanDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

}
