package com.example.greendaodemo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.greendaodemo.bean.Card2;

import com.example.greendaodemo.bean.User2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USERS2".
*/
public class User2Dao extends AbstractDao<User2, Long> {

    public static final String TABLENAME = "USERS2";

    /**
     * Properties of entity User2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CardId = new Property(1, Long.class, "cardId", false, "CARD_ID");
        public final static Property Usercode = new Property(2, String.class, "usercode", false, "USERCODE");
        public final static Property Name = new Property(3, String.class, "name", false, "userName");
        public final static Property UserAddress = new Property(4, String.class, "userAddress", false, "USER_ADDRESS");
    }

    private DaoSession daoSession;


    public User2Dao(DaoConfig config) {
        super(config);
    }
    
    public User2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USERS2\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_ID\" INTEGER," + // 1: cardId
                "\"USERCODE\" TEXT," + // 2: usercode
                "\"userName\" TEXT NOT NULL ," + // 3: name
                "\"USER_ADDRESS\" TEXT);"); // 4: userAddress
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "usercode_index2 ON \"USERS2\"" +
                " (\"USERCODE\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_USERS2_userName_DESC ON \"USERS2\"" +
                " (\"userName\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USERS2\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindLong(2, cardId);
        }
 
        String usercode = entity.getUsercode();
        if (usercode != null) {
            stmt.bindString(3, usercode);
        }
        stmt.bindString(4, entity.getName());
 
        String userAddress = entity.getUserAddress();
        if (userAddress != null) {
            stmt.bindString(5, userAddress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User2 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindLong(2, cardId);
        }
 
        String usercode = entity.getUsercode();
        if (usercode != null) {
            stmt.bindString(3, usercode);
        }
        stmt.bindString(4, entity.getName());
 
        String userAddress = entity.getUserAddress();
        if (userAddress != null) {
            stmt.bindString(5, userAddress);
        }
    }

    @Override
    protected final void attachEntity(User2 entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User2 readEntity(Cursor cursor, int offset) {
        User2 entity = new User2( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // cardId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // usercode
            cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // userAddress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User2 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUsercode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.getString(offset + 3));
        entity.setUserAddress(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User2 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCard2Dao().getAllColumns());
            builder.append(" FROM USERS2 T");
            builder.append(" LEFT JOIN CARD2 T0 ON T.\"CARD_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected User2 loadCurrentDeep(Cursor cursor, boolean lock) {
        User2 entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Card2 card = loadCurrentOther(daoSession.getCard2Dao(), cursor, offset);
        entity.setCard(card);

        return entity;    
    }

    public User2 loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<User2> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<User2> list = new ArrayList<User2>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<User2> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<User2> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
